apiVersion: apps/v1
kind: Deployment
metadata:
  name: eash-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eash-api
  template:
    metadata:
      labels:
        app: eash-api
    spec:
      containers:
      - name: eash-api
        image: placeholder
        imagePullPolicy: Never
        ports:
        - containerPort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: eash-api-service
spec:
  selector:
    app: eash-api
  ports:
    - protocol: TCP
      port: 30081
      targetPort: 30081
      nodePort: 30081  # Specify the node port if desired
  type: NodePort