apiVersion: apps/v1
kind: Deployment
metadata:
  name: eash-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eash-site
  template:
    metadata:
      labels:
        app: eash-site
    spec:
      containers:
      - name: eash-site
        image: placeholder
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eash-site-service
spec:
  selector:
    app: eash-site
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 80
      nodePort: 30080  # Specify the node port if desired
  type: NodePort
